#include <R.h>
#include <Rinternals.h>
#include <stdlib.h> // for NULL
#include <R_ext/Rdynload.h>

/* pkgbuild::compile_dll(force = TRUE, register_routines = TRUE)*/
/* Section generated by pkgbuild, do not edit */
/* .Call calls */
extern SEXP allfuns(SEXP, SEXP, SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"allfuns", (DL_FUNC) &allfuns, 3},
    {NULL, NULL, 0}
};
/* End section generated by pkgbuild */

void R_init_svMisc(DllInfo *dll)
{
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
